export enum ExceptionsEnum {
  INTERNAL_SERVICE_ERROR = 'INTERNAL_SERVICE_ERROR',
  TARGET_LIST_FILE_ERROR = 'TARGET_LIST_FILE_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
